### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by kirill-sizov** [kirill-sizov/ksizovcvat#1]
- [ ] Add security scans for Docker image
- [ ] Eliminate from duplication in workflow configs
- [ ] Remove autogenerated tests.rego files
- [ ] Try to add one more docker image with name `cvat_base` that will contain general code dependencies that rarely updates
